src/blood_bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path
from donor.views import (
                        PersonCreateView,
                        load_ps,
                        home_page,
                        search_result
                    )


urlpatterns = [
    path('', home_page,name="home"),
    path('admin/', admin.site.urls),
    path('register/', PersonCreateView.as_view(),name="register"),
    path('search/', search_result,name="search-result"),
    path('ajax/load-dist/', load_ps, name='ajax_load_ps'),
    path('eligibility/', TemplateView.as_view(template_name="eligibility.html"),name="eligibility"),
    path('contact/', TemplateView.as_view(template_name="contact.html"),name="contact"),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/donor/models.py
from django.db import models



BLOOD_GROUP_LIST = [

    ("a+","A+"),
    ("a-","A-"),
    ("b+","B+"),
    ("b-","B-"),
    ("o+","O+"),
    ("o-","O-"),
    ("ab+","AB+"),
    ("ab-","AB-"),
]

class Distict(models.Model):
    name        = models.CharField(max_length=220)

    class Meta:
        ordering = ["name"]


    def __str__(self):
        return str(self.name)


class PoliceStation(models.Model):
    distict     = models.ForeignKey(Distict,on_delete = models.CASCADE) 
    name        = models.CharField(max_length=220)

    class Meta:
        ordering = ["name"]
    
    def __str__(self):
        return str(self.name)


class Donar(models.Model):
    name                = models.CharField(max_length=220)
    mobile_number_1     = models.CharField(max_length=220)
    mobile_number_2     = models.CharField(max_length=220,null=True,blank=True)
    blood_group         = models.CharField(max_length=220,choices=BLOOD_GROUP_LIST)
    address             = models.CharField(max_length=220)
    distict             = models.ForeignKey(Distict, on_delete=models.SET_NULL, null=True)
    police_station      = models.ForeignKey(PoliceStation, on_delete=models.SET_NULL, null=True)
    
    class Meta:
        ordering = ["blood_group"]
    
    def __str__(self):
        return self.name

src/donor/forms.py
from django import forms
from .models import Donar, PoliceStation

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Donar
        fields = ('name', 'mobile_number_1', 'mobile_number_2', 'blood_group','address','distict','police_station')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['police_station'].queryset = PoliceStation.objects.none()
        
        
        if 'distict' in self.data:
            try:
                country_id = int(self.data.get('distict'))
                self.fields['police_station'].queryset = PoliceStation.objects.filter(distict_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['distict'].queryset = self.instance.distict.police_station_set.order_by('name')

src/donor/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.urls import reverse
from .models import Donar,Distict,PoliceStation
from .forms import RegistrationForm


class PersonCreateView(SuccessMessageMixin,CreateView):
    form_class = RegistrationForm
    template_name = "registration.html"
    success_message = "Thanks for registration."

    def get_success_url(self):
        return reverse('home')

def load_ps(request):
    dist_id = request.GET.get('distict')
    police_station = PoliceStation.objects.filter(distict_id=dist_id).order_by('name')
    return render(request, 'dropdown_list_options.html', {'police_station': police_station})



def home_page(request):
    all_dist = Distict.objects.all()

    if request.method == "POST":
        blood_group = request.POST.get("blood_group")

        dist_id = request.POST.get("distict")
        dist_qs = Distict.objects.get(id=dist_id)

        police_id = request.POST.get("police_station")
        ps_qs = PoliceStation.objects.get(id=police_id)

        qs = Donar.objects.filter(
                                blood_group=blood_group,
                                distict__exact = dist_qs,
                                police_station__exact= ps_qs
                                )
      
    template_name = "index.html"
    context = {
        "all_dist":all_dist,

    }
    return render(request,template_name,context)


def search_result(request):
    result = None
    try:
        if request.method == "POST":
            blood_group = request.POST.get("blood_group")

            dist_id = request.POST.get("distict")
            dist_qs = Distict.objects.get(id=dist_id)

            police_id = request.POST.get("police_station")
            ps_qs = PoliceStation.objects.get(id=police_id)

            qs = Donar.objects.filter(
                                    blood_group=blood_group,
                                    distict__exact = dist_qs,
                                    police_station__exact= ps_qs
                                    )

            result = qs 
    except:
        pass

    template_name = "search_result.html"
    context = {
        "result":result,
    }
    return render(request,template_name,context)

src/templates/contact.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static "main.css" %}">
  <link rel='icon' href='{% static "favicon.ico" %}' type='image/x-icon'/ >
  <title>Save a Life | Contact</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url "home" %}" style="color:red;"><img src="{% static "logo2.png" %}" alt="" width="150" height="50" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% include "nav-bar.html" %}
    </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-12" id="main">
      <h3 align="center" id="caps">CONTACT US</h3>
      <h4 align="center">If you have any query, please feel free to contact with us.</h4>
      <section class="search-sec-table">
          <div class="container">
            <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th scope="col">Mobile</th>
                        <th scope="col">Email</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>01630603018</td>
                        <td>admin@raselsplanet.com</td>
                      </tr>
                    </tbody>
                 </table>
          </div>
      </section>
    </div>
  </div>
</div>
    
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1" style="color:red;">&copy; 2019 <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasels Planet</a>. All rights reserved | Developed By <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasel Miah</a> </p>
</footer>
{% include "footer-js.html" %}
</body>
</html>

src/templates/dropdown_list_options.html
<option value="">Select Thana</option>
{% for obj in police_station %}
<option value="{{ obj.id }}">{{ obj.name }}</option>
{% endfor %}

src/templates/eligibility.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static "main.css" %}">
  <link rel='icon' href='{% static "favicon.ico" %}' type='image/x-icon'/ >
  <title>Save a Life | Donation Eligibility</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url "home" %}" style="color:red;"><img src="{% static "logo2.png" %}" alt="" width="150" height="50" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% include "nav-bar.html" %}
    </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-12" id="main">
      <h3 align="center" id="caps">DONATION ELIGIBILITY</h3>
      <section class="search-sec-table">
          <div class="container" id="about">
                <a href="{% url "home" %}"><img src="{% static "logo2.png" %}" alt=""  class="float-left" width="45%"></a>
                <h2>What is "Save a Life" ?</h2>
                <p><strong>Save a Life</strong> is a non-profit blood donation system where anyone can register as a blood donor. Anyone who needs blood, can search blood group to his location. No need to sign in/sign up. </p>
                <h2>Who can donate blood ?</h2>
                <p>To donate blood,you must be in good general health, weigh at least 110 pounds, and be at least 16 years old.Good health means that you feel well and are able to carry out normal daily activities. If you have a chronic medical condition such as diabetes or high blood pressure, you may still be eligible as long as you are receiving treatment to control your condition.</p>
                <p><strong>Age:</strong> You must be at least 17 years old to donate to the general blood supply. There is no upper age limit for blood donation as long as you are well with no restrictions or limitations to your activities.</p> 
                <p><strong>High Blood Pressure:</strong> Acceptable as long as your blood pressure is below 180 systolic (first number) and below 100 diastolic (second number) at the time of donation. Medications for high blood pressure do not disqualify you from donating.</p> 
                <p><strong>Body Piercing:</strong> You must not donate if you have had a tongue, nose, belly button or genital piercing in the past 12 months (donors with pierced ears are eligible).</p>
                <p><strong>Cold and Flu</strong>: Wait if you have a fever or a productive cough (bringing up phlegm). Wait if you do not feel well on the day of donation. Wait until you have completed antibiotic treatment for sinus, throat or lung infection.</p> 
                <img src="{% static "img1.png" %}" alt=""  class="float-right" width="50%">
                <p><strong>Diabetes:</strong> Acceptable as long as it is well controlled, whether medication is taken or not.</p>
                <p><strong>Diet:</strong> A meal is recommended at least four hours prior to donation. Drink plenty of fluids.</p>
                <p><strong>MSM:</strong> Men who have had sex with other men, at any time since 1977 (the beginning of the AIDS epidemic in the United States) are currently deferred as blood donors. This is because MSM are, as a group, at increased risk for HIV, hepatitis B and certain other infections that can be transmitted by transfusion.</p>
                <p><strong>Tattoos:</strong> One-year deferral.</p>
                <p><strong>Travel:</strong> Please refer to <a href="https://www.cdc.gov/malaria/blood_banks.html">Centers for Disease Control and Prevention</a>. If you need further assistance please call UCSF Blood Center (415) 353-1809.</p>
                <p><strong>Weight:</strong> You must weigh at least 110 pounds to be eligible for blood donation for your own safety. Blood volume is in proportion to body weight. Donors who weigh less than 110 pounds may not tolerate the removal of the required volume of blood as well as those who weigh more than 110 pounds. There is no upper weight limit as long as your weight is not higher than the weight limit of the donor bed or lounge you are using. You can discuss any upper weight limitations of beds and lounges with your local health historian.</p> 

                <p>Other criteria that will be assessed at the time of donation such as (list is not all inclusive):</p>

                <p>Hemoglobin, Travel, Cancer, Medications, Hepatitis, and HIV Risk:</p>

                <p><ul id="bullet"><li>Intravenous drug abusers: HIV, HBV, HCV and HTLV</li>
                <li>Transplant patients: animal tissue or organs</li>
                <li>People who have recently traveled to or lived abroad in certain countries may be excluded because they are at risk for transmitting agents such as malaria or variant Creutzfeldt-Jakob Disease (vCJD).</li></ul></p>

                <p>&nbsp;</p><p>Reviewed by health care specialists at UCSF Medical Center.</p>

                <p><strong>This information is for educational purposes only and is not intended to replace the advice of your doctor or health care provider.  We encourage you to discuss with your doctor any questions or concerns you may have</strong>.</p>

                <h2>What Conditions Would Make You Ineligible to Be a Donor?</h2>
                <p>You will not be eligible to donate blood or platelets if you:</p>
                <img src="{% static "img2.jpg" %}" alt=""  class="float-right" width="50%">
                <ul>
                    <li >Have tested positive for hepatitis B or hepatitis C, lived with or had sexual contact in the past 12 months with anyone who has hepatitis B or symptomatic hepatitis C.</li>
                    <li>Had a tattoo in the past 12 months or received a blood transfusion (except with your own blood) in the past 12 months.</li>
                    <li>Have ever had a positive test for the AIDS virus.</li>
                    <li>Are a man who has had sex with another man in the past 12 months.</li>
                    <li>Have ever used intravenous illegal drugs, even once.</li>
                    <li>Have ever used injectable drugs, including anabolic steroids, unless prescribed by a physician.</li>
                    <li>Have engaged in prostitution since 1977.</li>
                    <li>Have traveled in the past year, or lived in the past three years, in an area where malaria is endemic.</li>
          </div>
      </section>
    </div>
  </div>
</div>
    
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1" style="color:red;">&copy; 2019 <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasels Planet</a>. All rights reserved | Developed By <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasel Miah</a> </p>
</footer>
{% include "footer-js.html" %}
</body>
</html>

src/templates/footer-js.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
  $("#id_distict").change(function () {
    var url = $("#personForm").attr("data-cities-url");  
    var countryId = $(this).val(); 

    $.ajax({                      
      url: url,                   
      data: {
        'distict': countryId       
      },
      success: function (data) {  
        $("#id_police_station").html(data);  
      }
    });

  });
</script>

src/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static "main.css" %}">
  <link rel='icon' href='{% static "favicon.ico" %}' type='image/x-icon'/ >
  <title>Save a Life</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url "home" %}" style="color:red;"><img src="{% static "logo2.png" %}" alt="" width="150" height="50" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% include "nav-bar.html" %}
    </div>
</nav>

{% if messages %}
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h2>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</h2> {{ message }}
  </div>
  {% endfor %}
{% endif %}

<div class="container">
  <div class="row">
    <div class="col-sm-12" id="main">
      <img src="{% static "logo.jpg" %}" alt="" class="center">
      <h3 align="center" id="caps">
        SEARCH BLOOD DONOR TO YOUR LOCATION 
      </h3>
      <section class="search-sec">
          <div class="container">
              <form method="POST" id="personForm" data-cities-url="{% url 'ajax_load_ps' %}" action="{% url "search-result" %}" novalidate>
                  {% csrf_token %}
                  <div class="row">
                      <div class="col-lg-12">
                          <div class="row">
                              <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                  <select name="blood_group" required id="id_blood_group" class="form-control search-slt">
                                      <option value="" selected>Select Blood Group</option>
                                    
                                      <option value="a+">A+</option>
                                    
                                      <option value="a-">A-</option>
                                    
                                      <option value="b+">B+</option>
                                    
                                      <option value="b-">B-</option>
                                    
                                      <option value="o+">O+</option>
                                    
                                      <option value="o-">O-</option>
                                    
                                      <option value="ab+">AB+</option>
                                    
                                      <option value="ab-">AB-</option>
                                    
                                    </select>
                              </div>
                               <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                  <select name="distict" required id="id_distict" class="form-control search-slt">
                                      <option value="" selected>Select Distict</option>
                                      {% for ob in all_dist %}
                                      <option value="{{ ob.id }}">{{ob.name }}</option>
                                      {% endfor %}
                                    </select>
                              </div>
                                <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                    <select name="police_station" required id="id_police_station" class="form-control search-slt">
                                        <option value="" selected>------------</option>
                                      
                                      </select>
                              </div>
                              <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                  <button type="submit" class="btn btn-danger wrn-btn">Search</button>
                              </div>
                          </div>
                      </div>
                  </div>
              </form>
          </div>
      </section>
    </div>
  </div>
</div>
    
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1" style="color:red;">&copy; 2019 <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasels Planet</a>. All rights reserved | Developed By <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasel Miah</a> </p>
</footer>
  {% include "footer-js.html" %}
</body>
</html>

src/templates/nav-bar.html
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="{% url "home" %}" style="color:red;">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "eligibility" %}" style="color:red;">Donation Eligibility</a>
      </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "register" %}" style="color:red;">Become a Donor</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "contact" %}" style="color:red;">Contact</a>
      </li>
</ul>

src/templates/registration.html
{% load static %}
{% load custom_tags %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static "main.css" %}">
  <link rel='icon' href='{% static "favicon.ico" %}' type='image/x-icon'/ >
  <title>Save a Life | Registration</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url "home" %}" style="color:red;"><img src="{% static "logo2.png" %}" alt="" width="150" height="50" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% include "nav-bar.html" %}
    </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 align="center" id="caps">BECOME A DONOR</h3> 
        <div class="row">
            <div class="col-sm-4">
                <img src="{% static "krv.jpg" %}" alt="" width="100%" height="70%">
              </div>
            <div class="col-sm-8">
                <h4>Before registration, please read the <a href="{% url "eligibility" %}" target="_blank">eligibility</a> to become a donor.</h4>
                <form method="POST" id="personForm" data-cities-url="{% url 'ajax_load_ps' %}"  novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <input type="submit" class="btn btn-success" value="Register">
                </form>
            </div>
        </div>
    </div>
  </div>
</div>
    
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1" style="color:red;">&copy; 2019 <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasels Planet</a>. All rights reserved | Developed By <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasel Miah</a> </p>
</footer>
{% include "footer-js.html" %}
</body>
</html>

src/templates/search_result.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static "main.css" %}">
  <link rel='icon' href='{% static "favicon.ico" %}' type='image/x-icon'/ >
  <title>Save a Life | Donor List</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url "home" %}" style="color:red;"><img src="{% static "logo2.png" %}" alt="" width="150" height="50" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% include "nav-bar.html" %}
    </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-12" id="main">
      <h3 align="center" id="caps">
        DONOR LIST 
        </h3>
      <section class="search-sec-table">
          <div class="table-responsive">
            {% if result is None %}
                <p>You haven't search yet</p>
                <br>
            {% else %}
            <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Blood Group</th>
                        <th scope="col">Mobile</th>
                        <th scope="col">Location</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for ob in result %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ ob.name }}</td>
                        <td>{{ ob.blood_group|uppercase }}</td>
                        <td>{{ ob.mobile_number_1 }} , {{ ob.mobile_number_2 }}</td>
                        <td>{{ ob.address }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            {% endif %}
          </div>
      </section>
    </div>
  </div>
</div>
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1" style="color:red;">&copy; 2019 <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasels Planet</a>. All rights reserved | Developed By <a href="http://raselsplanet.com/" target="_blank" style="color:red;">Rasel Miah</a> </p>
</footer>
{% include "footer-js.html" %}
</body>
</html>